services:
    database:
        image: mysql:lts
        restart: always
        container_name: database
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: default
        volumes:
            - ./migrations:/docker-entrypoint-initdb.d:ro
