CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    balance DECIMAL(19,4) NOT NULL DEFAULT 0,

    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS bets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    betAmount DECIMAL(19,4) NOT NULL,
    chance FLOAT NOT NULL,
    payout DECIMAL(19,4) NOT NULL,
    win BOOLEAN NOT NULL,
    userId BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY(id),
    FOREIGN KEY (userId) REFERENCES users(id)
);